version: '3.8'

services:
  web:
    build: .
    image: brozjay/my-web-app:latest
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
